java:
  applicationPort: 4104
  readinessDelay: 180
  livenessDelay: 180
  readinessPeriod: 60
  livenessPeriod: 60
  ingressHost: probate-back-office-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: back-office
    AUTH_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PDF_SERVICE_URL: http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PRINTSERVICE_HOST: https://return-case-doc-ccd.nonprod.platform.hmcts.net
    PRINTSERVICE_INTERNAL_HOST: http://ccd-case-print-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_SERVICE_HOST: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    FEE_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    EVIDENCE_MANAGEMENT_HOST: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_GATEWAY_HOST: http://ccd-api-gateway-web-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SEND_LETTER_SERIVCE_BASEURL: http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_CORECASEDATA_BASEURL : http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCD_DATA_STORE_API_HOST : http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal 
    LOG_LEVEL: DEBUG
    AUTH_S2S_CLIENT_ID: "probate_backend"
    IDAM_CLIENT_NAME: "probate"
  keyVaults:
    "probate":
      resourceGroup: probate
      secrets:
        - s2s-probate-backend
        - AppInsightsInstrumentationKey
        - probate-bo-govNotifyApiKey
        - probate-bo-grantSignatureKey
        - probate-bo-grantSignatureFile
        - probatemandb-POSTGRES-USER
        - probatemandb-POSTGRES-PASS
        - probatemandb-POSTGRES-HOST
        - probatemandb-POSTGRES-PORT
        - probatemandb-POSTGRES-DATABASE
        - excelaEmail
        - authTokenEmail
        - authTokenPassword
        - ftpSignature
        - ftpEnv
        - pdfServiceBaseUrl
        - pdfServiceAccessKey
        - pdfServiceHealthUrl
        - idamRedirectUrl
        - idam-secret-probate
  image: hmctspublic.azurecr.io/probate/back-office:latest

