tags:
  - idam-pr

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    probatemandb-POSTGRES-USER: "{{ .Values.postgresql.postgresqlUsername}}"
    probatemandb-POSTGRES-PASS: "{{ .Values.postgresql.postgresqlPassword}}"
    probatemandb-POSTGRES-HOST: "{{ .Release.Name }}-postgresql"
    probatemandb-POSTGRES-DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
  
  postgresql:
    enabled: true


