java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  environment:
    PROBATE_POSTGRESQL_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    PROBATE_POSTGRESQL_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    PROBATE_POSTGRESQL_HOSTNAME: "{{ .Release.Name }}-postgresql"
    PROBATE_POSTGRESQL_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    PROBATE_POSTGRESQL_PORT: 5432
    APPINSIGHTS_INSTRUMENTATIONKEY: dummy
  keyVaults:
    "probate":
      resourceGroup: probate
      secrets:
        - s2s-probate-backend
        - probate-bo-govNotifyApiKey
        - probate-bo-grantSignatureKey
        - probate-bo-grantSignatureFile
        - excelaEmail
        - authTokenEmail
        - authTokenPassword
        - ftpSignature
        - ftpEnv
        - pdfServiceBaseUrl
        - pdfServiceAccessKey
        - pdfServiceHealthUrl
        - idamRedirectUrl
        - idam-secret-probate
  postgresql:
    enabled: true

