java:
  applicationPort: 4104
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: back-office
    LOG_LEVEL: DEBUG
    APPINSIGHTS_INSTRUMENTATIONKEY: dummy
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${S2S_AUTH_TOTP_SECRET}
    NOTIFICATIONS_GOVNOTIFYAPIKEY: ${PROBATE_BO_NOTIFY_KEY}
    PDF_SERVICE_GRANTSIGNATUREBASE64: ${BO_GRANT_SIG_FIRST}${BO_GRANT_SIG_LAST}
    PROBATE_POSTGRESQL_USER_VAL: probateman
    PROBATE_POSTGRESQL_PASSWORD_VAL: probateman
    PROBATE_POSTGRESQL_HOSTNAME_VAL: ${SERVICE_NAME}-postgres
    PROBATE_POSTGRESQL_PORT_VAL: 5432
    PROBATE_POSTGRESQL_DATABASE_VAL: probateman
  # Don't modify below here.
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

ccd-elasticsearch:
  ccd:
    ingressHost: ${SERVICE_FQDN}
    ingressIP: ${INGRESS_IP}
    consulIP: ${CONSUL_LB_IP}

    definitionStoreApi:
      s2sKey: ${DEFINITION_STORE_S2S_KEY}

    apiGateway:
      s2sKey: ${API_GATEWAY_S2S_KEY}
      idamClientSecret: ${API_GATEWAY_IDAM_SECRET}

    dataStoreApi:
      s2sKey: ${DATA_STORE_S2S_KEY}
      image: "hmcts.azurecr.io/hmcts/ccd-data-store-api:tim-debug"

    caseManagementWeb:
      enabled: true

    printApi:
      enabled: true # if you need access to the case print service then enable this
      s2sKey: ${PRINT_S2S_KEY}
      probateTemplateUrl: http://print-api-${SERVICE_FQDN}

    importer:
      definitions:
        - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_V04.32.01-Hlm.xlsx
      # location incorrect.. its not in b-o, do we need this sheet?   - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_Legacy_V00.01-Dev.xlsx
      #      - https://github.com/hmcts/Probate-CCD-Import-Spreadsheets/raw/master/spreadsheet/CCD_Probate_V21.02-Dev.xlsx
      userRoles:
        - caseworker-probate
        - caseworker-probate-issuer
        - caseworker-probate-solicitor
        - citizen
        - caseworker-probate-examiner

postgresql:
  postgresqlUsername: probateman
  postgresqlPassword: probateman
  postgresqlDatabase: probateman
  nameOverride: postgres
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "probateman" WITH OWNER = probate ENCODING = 'UTF-8' CONNECTION LIMIT = -1;

  persistence:
    enabled: false
